# Generated by Django 5.2.12 on 2026-05-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_advertisement_sponsor_alter_book_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile / 用户资料', 'verbose_name_plural': 'User Profiles / 用户资料列表'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio / 自我介绍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200, verbose_name='College / Faculty / 学院'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('elem', 'Elementary School / 小学'), ('middle', 'Middle School / 初中'), ('hs', 'High School / 高中'), ('1', 'Freshman / 大一'), ('2', 'Sophomore / 大二'), ('3', 'Junior / 大三'), ('4', 'Senior / 大四'), ('ms1', "Master's Year 1 / 硕士一年级"), ('ms2', "Master's Year 2 / 硕士二年级"), ('ms3', "Master's Year 3 / 硕士三年级"), ('phd1', 'PhD Year 1 / 博士一年级'), ('phd2', 'PhD Year 2 / 博士二年级'), ('phd3', 'PhD Year 3 / 博士三年级'), ('phd4', 'PhD Year 4 / 博士四年级'), ('phd5', 'PhD Year 5+ / 博士五年级及以上')], max_length=10, verbose_name='Grade / 年级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major / 专业'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone / 电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.university', verbose_name='University / 学校'),
        ),
    ]
