# Generated by Django 5.2.12 on 2026-05-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('elem', 'Elementary School'), ('middle', 'Middle School'), ('hs', 'High School'), ('1', 'Freshman (Year 1)'), ('2', 'Sophomore (Year 2)'), ('3', 'Junior (Year 3)'), ('4', 'Senior (Year 4)'), ('ms1', "Master's Year 1"), ('ms2', "Master's Year 2"), ('ms3', "Master's Year 3"), ('phd1', 'PhD Year 1'), ('phd2', 'PhD Year 2'), ('phd3', 'PhD Year 3'), ('phd4', 'PhD Year 4'), ('phd5', 'PhD Year 5+')], max_length=10, verbose_name='Grade / 年级'),
        ),
    ]
