# Generated by Django 4.2.30 on 2026-06-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_major'),
        ('users', '0003_alter_userprofile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.college', verbose_name='College / Faculty / 学院'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.major', verbose_name='Major / 专业'),
        ),
    ]
