# Generated by Django 5.2.12 on 2026-05-28 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad Title / 广告标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Ad Image / 广告图片')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL / 广告链接')),
                ('advertiser_name', models.CharField(blank=True, max_length=200, verbose_name='Advertiser / 广告商名称')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Paid / 广告费用')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / 是否展示')),
                ('position', models.IntegerField(default=0, verbose_name='Position / 排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At / 到期时间')),
            ],
            options={
                'verbose_name': 'Advertisement / 广告',
                'verbose_name_plural': 'Advertisements / 广告列表',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name / 赞助商名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/', verbose_name='Logo / 标志图片')),
                ('website', models.URLField(blank=True, verbose_name='Website / 官网链接')),
                ('tier', models.CharField(choices=[('platinum', 'Platinum / 铂金赞助'), ('gold', 'Gold / 黄金赞助'), ('silver', 'Silver / 白银赞助'), ('bronze', 'Bronze / 青铜赞助'), ('donor', 'Individual Donor / 个人捐赠者')], default='bronze', max_length=10, verbose_name='Tier / 赞助等级')),
                ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount / 赞助金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / 是否展示')),
                ('message', models.TextField(blank=True, verbose_name='Message / 赞助商寄语')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor / 赞助商',
                'verbose_name_plural': 'Sponsors / 赞助商列表',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book / 书籍', 'verbose_name_plural': 'Books / 书籍列表'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'University / 大学', 'verbose_name_plural': 'Universities / 大学列表'},
        ),
        migrations.AddField(
            model_name='book',
            name='college',
            field=models.CharField(blank=True, max_length=200, verbose_name='College / Faculty / 学院'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Platform Fee (5%) / 平台服务费'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author / 作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('arts', 'Arts & Humanities / 文学艺术'), ('business', 'Business & Management / 商业管理'), ('cs', 'Computer Science & IT / 计算机'), ('math', 'Mathematics & Statistics / 数学统计'), ('engineering', 'Engineering / 工程'), ('education', 'Education / 教育'), ('social', 'Social Sciences / 社会科学'), ('natural', 'Natural Sciences / 自然科学'), ('health', 'Health & Medicine / 医学健康'), ('other', 'Other / 其他')], max_length=20, verbose_name='Category / 分类'),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('like_new', 'Like New / 九成新 (98%)'), ('good', 'Good / 七八成新 (85%)'), ('used', 'Used / 六成新 (70%)')], default='good', max_length=10, verbose_name='Condition / 成色'),
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.CharField(blank=True, max_length=200, verbose_name='Course / 课程'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover Image / 封面图'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Listed At / 上架时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / 描述'),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('elem', 'Elementary School / 小学'), ('middle', 'Middle School / 初中'), ('hs', 'High School / 高中'), ('1', 'Freshman / 大一'), ('2', 'Sophomore / 大二'), ('3', 'Junior / 大三'), ('4', 'Senior / 大四'), ('ms1', "Master's Year 1 / 硕士一年级"), ('ms2', "Master's Year 2 / 硕士二年级"), ('ms3', "Master's Year 3 / 硕士三年级"), ('phd1', 'PhD Year 1 / 博士一年级'), ('phd2', 'PhD Year 2 / 博士二年级'), ('phd3', 'PhD Year 3 / 博士三年级'), ('phd4', 'PhD Year 4 / 博士四年级'), ('phd5', 'PhD Year 5+ / 博士五年级及以上')], max_length=10, verbose_name='Grade Level / 年级'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Is Sold / 已售'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price / 价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major / Program / 专业'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Seller / 卖家'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Book Title / 书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.university', verbose_name='University / 学校'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Published / 出版年份'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / 待确认'), ('confirmed', 'Confirmed / 已确认'), ('completed', 'Completed / 已完成'), ('cancelled', 'Cancelled / 已取消')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Abbreviation / 简称'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='Country / 国家'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / 简介'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='University Name / 学校名称'),
        ),
    ]
