# Generated by Django 5.2.12 on 2026-05-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_advertisement_sponsor_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Photo / 照片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption / 说明')),
                ('order', models.IntegerField(default=0, verbose_name='Order / 排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'verbose_name': 'Book Photo / 书籍照片',
                'verbose_name_plural': 'Book Photos / 书籍照片列表',
                'ordering': ['order', 'id'],
            },
        ),
    ]
