# Generated by Django 5.2.12 on 2026-05-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured (appears first)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('arts', 'Arts & Humanities'), ('business', 'Business & Management'), ('cs', 'Computer Science & IT'), ('math', 'Mathematics & Statistics'), ('engineering', 'Engineering'), ('education', 'Education'), ('social', 'Social Sciences'), ('natural', 'Natural Sciences'), ('health', 'Health & Medicine'), ('other', 'Other')], max_length=20, verbose_name='Category / 分类'),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('like_new', 'Like New (98%)'), ('good', 'Good (85%)'), ('used', 'Used (70%)')], default='good', max_length=10, verbose_name='Condition / 成色'),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('elem', 'Elementary School'), ('middle', 'Middle School'), ('hs', 'High School'), ('1', 'Freshman (Year 1)'), ('2', 'Sophomore (Year 2)'), ('3', 'Junior (Year 3)'), ('4', 'Senior (Year 4)'), ('ms1', "Master's Year 1"), ('ms2', "Master's Year 2"), ('ms3', "Master's Year 3"), ('phd1', 'PhD Year 1'), ('phd2', 'PhD Year 2'), ('phd3', 'PhD Year 3'), ('phd4', 'PhD Year 4'), ('phd5', 'PhD Year 5+')], max_length=10, verbose_name='Grade Level / 年级'),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='University Name'),
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='College Name')),
                ('abbreviation', models.CharField(blank=True, max_length=30, verbose_name='Abbreviation')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='books.university')),
            ],
            options={
                'verbose_name': 'College / Faculty',
                'verbose_name_plural': 'Colleges / Faculties',
                'ordering': ['name'],
                'unique_together': {('university', 'name')},
            },
        ),
    ]
