# Generated by Django 4.2.30 on 2026-06-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_university_options_university_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Major Name')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='books.college')),
            ],
            options={
                'verbose_name': 'Major / Program',
                'verbose_name_plural': 'Majors / Programs',
                'ordering': ['name'],
                'unique_together': {('college', 'name')},
            },
        ),
    ]
